package main

import (
	"context"
	"fmt"

	"github.com/rajveer43/goagentflow/memory/buffer"
	"github.com/rajveer43/goagentflow/memory/entity"
	"github.com/rajveer43/goagentflow/memory/inmemory"
	"github.com/rajveer43/goagentflow/memory/llmsummarizer"
	"github.com/rajveer43/goagentflow/memory/summary"
	"github.com/rajveer43/goagentflow/memory/window"
	"github.com/rajveer43/goagentflow/provider/anthropic"
	"github.com/rajveer43/goagentflow/runtime"
)

// Example demonstrates all advanced memory types in goagentflow.
// Shows how to use each memory backend for different use cases.
func main() {
	ctx := context.Background()

	fmt.Println("=== Advanced Memory Types Demo ===\n")

	// Example 1: Buffer Memory (FIFO sliding window)
	fmt.Println("1. Buffer Memory (Last N Messages)")
	fmt.Println("---")
	bufferMem := buffer.New(5) // Keep last 5 messages

	for i := 1; i <= 8; i++ {
		msg := runtime.Message{
			Role:    "user",
			Content: fmt.Sprintf("Message %d", i),
		}
		bufferMem.AddMessage(ctx, msg)
	}

	messages, _ := bufferMem.GetMessages(ctx)
	fmt.Printf("Added 8 messages, kept last 5: %d messages\n", len(messages))
	for i, msg := range messages {
		fmt.Printf("  %d. %s\n", i+1, msg.Content)
	}
	fmt.Println()

	// Example 2: Window Memory (Token-aware)
	fmt.Println("2. Window Memory (Token-Aware)")
	fmt.Println("---")
	windowMem := window.New(100) // Keep ~100 tokens

	longMessage1 := "The quick brown fox jumps over the lazy dog. The dog was sleeping under a tree in the forest."
	longMessage2 := "A beautiful sunset appeared on the horizon with colors of orange, red, and purple."
	longMessage3 := "The birds were singing their evening songs before heading to their nests."

	windowMem.AddMessage(ctx, runtime.Message{Role: "user", Content: longMessage1})
	windowMem.AddMessage(ctx, runtime.Message{Role: "user", Content: longMessage2})
	windowMem.AddMessage(ctx, runtime.Message{Role: "user", Content: longMessage3})

	tokens, _ := windowMem.EstimateTokens(ctx)
	msgs, _ := windowMem.GetMessages(ctx)
	fmt.Printf("Window capacity: 100 tokens, current: %d tokens, messages: %d\n", tokens, len(msgs))
	for i, msg := range msgs {
		fmt.Printf("  %d. %s...\n", i+1, msg.Content[:min(len(msg.Content), 50)])
	}
	fmt.Println()

	// Example 3: Entity Memory (Tracks named entities)
	fmt.Println("3. Entity Memory (Named Entity Tracking)")
	fmt.Println("---")
	baseMem := inmemory.New()
	entityMem := entity.New(baseMem)

	entityMem.AddMessage(ctx, runtime.Message{
		Role:    "user",
		Content: "Hello, I'm Alice Smith from San Francisco. I met Bob Johnson yesterday.",
	})
	entityMem.AddMessage(ctx, runtime.Message{
		Role:    "assistant",
		Content: "Nice to meet you Alice! San Francisco is a great city. How was your meeting with Bob?",
	})

	entities, _ := entityMem.GetEntities(ctx)
	fmt.Printf("Tracked entities: %d\n", len(entities))
	for name, info := range entities {
		fmt.Printf("  - %s (%s): mentioned %d times\n", name, info.Type, info.Mentions)
	}
	fmt.Println()

	// Example 4: Summary Memory (LLM-based summarization)
	fmt.Println("4. Summary Memory (Auto-Summarization)")
	fmt.Println("---")
	baseMemForSummary := inmemory.New()

	// Create an LLM-based summarizer (using Anthropic as example)
	llm := anthropic.New("your-api-key", "claude-opus-4-6")
	summarizer := llmsummarizer.New(llm)

	summaryMem := summary.New(baseMemForSummary, summarizer, 3) // Summarize after 3 messages

	summaryMem.AddMessage(ctx, runtime.Message{
		Role:    "user",
		Content: "I'm planning a trip to Japan.",
	})
	summaryMem.AddMessage(ctx, runtime.Message{
		Role:    "assistant",
		Content: "That sounds exciting! Japan has amazing culture, food, and technology.",
	})
	summaryMem.AddMessage(ctx, runtime.Message{
		Role:    "user",
		Content: "I'm thinking of visiting Tokyo, Kyoto, and Osaka.",
	})
	summaryMem.AddMessage(ctx, runtime.Message{
		Role:    "assistant",
		Content: "Great choices! Those are the three must-visit cities.",
	})

	msgs, _ = summaryMem.GetMessages(ctx)
	fmt.Printf("Summary memory has %d messages (with auto-summarization at 3+ messages)\n", len(msgs))

	// Try to get the summary (would be empty in stub version)
	if summary, err := summaryMem.GetSummary(ctx); err == nil && summary != "" {
		fmt.Printf("Summary:\n%s\n", summary)
	} else {
		fmt.Println("(Summary would be generated by LLM in production)")
	}
	fmt.Println()

	// Example 5: Combining multiple memory types
	fmt.Println("5. Composite Memory Setup")
	fmt.Println("---")

	// Create a stack: inmemory -> entity tracking -> window management
	compositeBase := inmemory.New()
	compositeWithEntity := entity.New(compositeBase)

	compositeWithEntity.AddMessage(ctx, runtime.Message{
		Role:    "user",
		Content: "I'm Sarah working at Google in Mountain View.",
	})
	compositeWithEntity.AddMessage(ctx, runtime.Message{
		Role:    "assistant",
		Content: "Google in Mountain View is the headquarters of a great company!",
	})

	compositeMessages, _ := compositeWithEntity.GetMessages(ctx)
	compositeEntities, _ := compositeWithEntity.GetEntities(ctx)

	fmt.Printf("Composite setup: %d messages, %d entities tracked\n", len(compositeMessages), len(compositeEntities))
	for name, info := range compositeEntities {
		if info.Mentions > 0 {
			fmt.Printf("  - %s (%s)\n", name, info.Type)
		}
	}
	fmt.Println()

	// Example 6: Key-Value Store (all memories support this)
	fmt.Println("6. Key-Value Store in Memory")
	fmt.Println("---")

	kvMem := inmemory.New()
	kvMem.Set(ctx, "user_preferences", map[string]interface{}{
		"language": "English",
		"timezone": "PST",
	})
	kvMem.Set(ctx, "session_id", "sess_12345")

	if val, err := kvMem.Get(ctx, "session_id"); err == nil {
		fmt.Printf("Retrieved session_id: %v\n", val)
	}
	if val, err := kvMem.Get(ctx, "user_preferences"); err == nil {
		fmt.Printf("Retrieved preferences: %v\n", val)
	}
	fmt.Println()

	// Example 7: Memory Interface Compliance
	fmt.Println("7. All Memory Types Implement runtime.Memory")
	fmt.Println("---")

	memoryTypes := []struct {
		name   string
		memory runtime.Memory
	}{
		{"BufferMemory", buffer.New(10)},
		{"WindowMemory", window.New(4096)},
		{"EntityMemory", entity.New(inmemory.New())},
		{"InMemory", inmemory.New()},
		{"Summary (with wrap)", summary.New(inmemory.New(), nil, 10)},
	}

	for _, mt := range memoryTypes {
		// All satisfy the Memory interface
		mt.memory.AddMessage(ctx, runtime.Message{Role: "test", Content: "test"})
		msgs, _ := mt.memory.GetMessages(ctx)
		fmt.Printf("  %s: ✓ (has %d messages)\n", mt.name, len(msgs))
	}
	fmt.Println()

	fmt.Println("=== Advanced Memory Types Summary ===")
	fmt.Println("✓ BufferMemory - FIFO sliding window")
	fmt.Println("✓ WindowMemory - Token-aware sliding window")
	fmt.Println("✓ EntityMemory - Named entity extraction & tracking")
	fmt.Println("✓ SummaryMemory - LLM-based automatic summarization")
	fmt.Println("✓ CompressiveMemory - LLM-based message compression")
	fmt.Println("\nAll memory types are composable and can wrap other memory backends!")
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
